### ISSUE TITLE
Cannot start service

### ISSUE THREAD

**Issue by nitro-marky** [Colbydude/twitch-extension-vue-laravel-mix-boilerplate#1]
Hi,
everything starts building correctly until I hit this point:

```
ERROR: for twitchextensionvuelaravelmixboilerplate_boilerplatebackend_1  Cannot start service boilerplatebackend: driver failed programming external connectivity on endpoint twitchextensionvuelaravelmixboilerplate_boilerplatebackend_1 (72d4a3612f270f50b649dcca98e080d9f37a2a2926484809fe811eabbc41fec2): Error starting userland proxy: mkdir /port/tcp:0.0.0.0:8080:tcp:172.19.0.2:8080: input/output error

ERROR: for boilerplatebackend  Cannot start service boilerplatebackend: driver failed programming external connectivity on endpoint twitchextensionvuelaravelmixboilerplate_boilerplatebackend_1 (72d4a3612f270f50b649dcca98e080d9f37a2a2926484809fe811eabbc41fec2): Error starting userland proxy: mkdir /port/tcp:0.0.0.0:8080:tcp:172.19.0.2:8080: input/output error
```
Has anyone else had this problem?

**Comment by Colbydude** [comment]
I think this is the issue I ran into while trying to setup the extension on Windows a few weeks ago. I have since removed the need for Docker. I'll push an update in a bit that should fix your issues.

**Comment by Colbydude** [comment]
I've updated the repo to reflect the setup in the [official Twitch Hello World Sample](https://github.com/twitchdev/extensions-hello-world). This removes the dependency for Docker and lets you leverage Twitch's new [Developer Rig](https://github.com/twitchdev/developer-rig). It also shows more of the capabilities of what an extension has to offer.

I'm closing this issue for now, since it was related to Docker. Should you have any additional issues, feel free to reopen this.
